import type { SupportTech, SupportTicket } from './types';

export const techs: SupportTech[] = [
  { id: 'tec-1', name: 'Mariana Alves' },
  { id: 'tec-2', name: 'Diego Costa' },
  { id: 'tec-3', name: 'Fernanda Luz' },
  { id: 'tec-4', name: 'Paulo Nery' },
];

export const supportTickets: SupportTicket[] = [
  {
    id: 'sup-1',
    nome: 'Farmacia Nova Era',
    tipo: 'novo',
    status: 'active',
    csStatus: 'Briefing',
    produto: 'WhatsApp',
    respTec: 'tec-1',
    createdAt: '2026-03-05',
    tasks: [
      { id: 'sup-1-task-1', title: 'Kickoff inicial', done: true, endDate: '2026-03-07' },
      { id: 'sup-1-task-2', title: 'Mapeamento de processos', done: false, endDate: '2026-03-20' },
      { id: 'sup-1-task-3', title: 'Checklist de acessos', done: false, endDate: '2026-03-24' },
    ],
  },
  {
    id: 'sup-2',
    nome: 'Clinica Solar',
    tipo: 'inclusao',
    status: 'active',
    csStatus: 'Configuracao',
    produto: 'CRM',
    respTec: 'tec-2',
    createdAt: '2026-03-06',
    tasks: [
      { id: 'sup-2-task-1', title: 'Configurar pipeline', done: true, endDate: '2026-03-10' },
      { id: 'sup-2-task-2', title: 'Importar contatos', done: false, endDate: '2026-03-21' },
      { id: 'sup-2-task-3', title: 'Validar automacoes', done: false, endDate: '2026-03-25' },
    ],
  },
  {
    id: 'sup-3',
    nome: 'Atacado Prime',
    tipo: 'novo',
    status: 'active',
    csStatus: 'Treinamento',
    produto: 'Chatbot',
    respTec: 'tec-3',
    createdAt: '2026-03-08',
    tasks: [
      { id: 'sup-3-task-1', title: 'Treinamento comercial', done: true, endDate: '2026-03-14' },
      { id: 'sup-3-task-2', title: 'Treinamento suporte', done: true, endDate: '2026-03-18' },
      { id: 'sup-3-task-3', title: 'Ajustes finais', done: false, endDate: '2026-03-26' },
    ],
  },
  {
    id: 'sup-4',
    nome: 'Grupo Lumen',
    tipo: 'inclusao',
    status: 'active',
    csStatus: 'Go-live',
    produto: 'Automacao',
    respTec: 'tec-1',
    createdAt: '2026-03-10',
    tasks: [
      { id: 'sup-4-task-1', title: 'Publicar fluxo', done: true, endDate: '2026-03-14' },
      { id: 'sup-4-task-2', title: 'Monitorar primeiros envios', done: false, endDate: '2026-03-23' },
    ],
  },
  {
    id: 'sup-5',
    nome: 'Studio Fit',
    tipo: 'novo',
    status: 'active',
    csStatus: 'Configuracao',
    produto: 'WhatsApp',
    respTec: 'tec-4',
    createdAt: '2026-03-12',
    tasks: [
      { id: 'sup-5-task-1', title: 'Criar templates', done: false, endDate: '2026-03-19' },
      { id: 'sup-5-task-2', title: 'Integrar API', done: false, endDate: '2026-03-27' },
    ],
  },
  {
    id: 'sup-6',
    nome: 'Mercado Aurora',
    tipo: 'novo',
    status: 'done',
    csStatus: 'Concluido',
    produto: 'CRM',
    respTec: 'tec-1',
    createdAt: '2026-02-01',
    updatedAt: '2026-02-09',
    tasks: [
      { id: 'sup-6-task-1', title: 'Kickoff', done: true, endDate: '2026-02-02' },
      { id: 'sup-6-task-2', title: 'Configuracao', done: true, endDate: '2026-02-05' },
      { id: 'sup-6-task-3', title: 'Treinamento', done: true, endDate: '2026-02-08' },
    ],
  },
  {
    id: 'sup-7',
    nome: 'Papelaria Central',
    tipo: 'inclusao',
    status: 'done',
    csStatus: 'Concluido',
    produto: 'WhatsApp',
    respTec: 'tec-2',
    createdAt: '2026-02-14',
    updatedAt: '2026-02-27',
    tasks: [
      { id: 'sup-7-task-1', title: 'Mapeamento', done: true, endDate: '2026-02-16' },
      { id: 'sup-7-task-2', title: 'Ajustes', done: true, endDate: '2026-02-24' },
    ],
  },
  {
    id: 'sup-8',
    nome: 'Clinica Essence',
    tipo: 'novo',
    status: 'done',
    csStatus: 'Concluido',
    produto: 'Automacao',
    respTec: 'tec-3',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-08',
    tasks: [
      { id: 'sup-8-task-1', title: 'Configuracao inicial', done: true, endDate: '2026-03-02' },
      { id: 'sup-8-task-2', title: 'Treinamento', done: true, endDate: '2026-03-07' },
    ],
  },
  {
    id: 'sup-9',
    nome: 'Hotel Lago Azul',
    tipo: 'inclusao',
    status: 'done',
    csStatus: 'Concluido',
    produto: 'Chatbot',
    respTec: 'tec-4',
    createdAt: '2026-03-05',
    updatedAt: '2026-03-21',
    tasks: [
      { id: 'sup-9-task-1', title: 'Refinar intents', done: true, endDate: '2026-03-10' },
      { id: 'sup-9-task-2', title: 'Publicar bot', done: true, endDate: '2026-03-20' },
    ],
  },
  {
    id: 'sup-10',
    nome: 'Construtora Nexo',
    tipo: 'novo',
    status: 'done',
    csStatus: 'Concluido',
    produto: 'CRM',
    respTec: 'tec-1',
    createdAt: '2026-03-10',
    updatedAt: '2026-03-19',
    tasks: [
      { id: 'sup-10-task-1', title: 'Pipeline inicial', done: true, endDate: '2026-03-12' },
      { id: 'sup-10-task-2', title: 'Treinamento final', done: true, endDate: '2026-03-18' },
    ],
  },
];
