import type { DevTicket, DevUser, Sprint } from './types';

export const devUsers: DevUser[] = [
  { id: 'dev-1', name: 'Ana Souza' },
  { id: 'dev-2', name: 'Bruno Lima' },
  { id: 'dev-3', name: 'Carla Nunes' },
  { id: 'dev-4', name: 'Diego Rocha' },
];

export const sprints: Sprint[] = [
  {
    id: 'sp-23',
    name: 'Sprint 23',
    start: '2026-02-01',
    end: '2026-02-14',
    goal: 'Estabilizar notificacoes',
    closed: true,
  },
  {
    id: 'sp-24',
    name: 'Sprint 24',
    start: '2026-02-15',
    end: '2026-02-28',
    goal: 'Melhorar onboarding',
    closed: true,
  },
  {
    id: 'sp-25',
    name: 'Sprint 25',
    start: '2026-03-01',
    end: '2026-03-14',
    goal: 'Refinar CRM e automacoes',
    closed: true,
  },
  {
    id: 'sp-26',
    name: 'Sprint 26',
    start: '2026-03-15',
    end: '2026-03-28',
    goal: 'Entregar rotinas de suporte e faturamento',
    closed: false,
  },
];

export const devTickets: DevTicket[] = [
  {
    id: 101,
    title: 'Painel financeiro com resumo mensal',
    devStatus: 'Backlog',
    devType: 'Feature',
    category: 'Financeiro',
    complexity: 'Complexa',
    resp: 'dev-1',
    createdAt: '2026-03-16',
    deadline: '2026-04-02',
    totalPts: 8,
    sprintId: 'sp-26',
  },
  {
    id: 102,
    title: 'Ajustar filtros do dashboard comercial',
    devStatus: 'Em Desenvolvimento',
    devType: 'Task',
    category: 'Dashboard',
    complexity: 'Media',
    resp: 'dev-2',
    createdAt: '2026-03-15',
    deadline: '2026-03-25',
    totalPts: 3,
    sprintId: 'sp-26',
    docDone: true,
  },
  {
    id: 103,
    title: 'Corrigir bug de duplicidade no CRM',
    devStatus: 'Code Review',
    devType: 'Bug',
    category: 'CRM',
    complexity: 'Media',
    resp: 'dev-3',
    createdAt: '2026-03-12',
    deadline: '2026-03-21',
    totalPts: 3,
    sprintId: 'sp-26',
    criticalBug: true,
    incident: true,
  },
  {
    id: 104,
    title: 'Refatorar cards do dashboard principal',
    devStatus: 'QA',
    devType: 'Task',
    category: 'Dashboard',
    complexity: 'Simples',
    resp: 'dev-4',
    createdAt: '2026-03-14',
    deadline: '2026-03-27',
    totalPts: 2,
    sprintId: 'sp-26',
    docDone: true,
  },
  {
    id: 105,
    title: 'Implementar timeline de atendimento',
    devStatus: 'Concluido',
    devType: 'Feature',
    category: 'Suporte',
    complexity: 'Complexa',
    resp: 'dev-1',
    createdAt: '2026-03-02',
    updatedAt: '2026-03-11',
    deadline: '2026-03-12',
    totalPts: 8,
    sprintId: 'sp-25',
    docDone: true,
    compliment: true,
  },
  {
    id: 106,
    title: 'Corrigir status preso em implantacao',
    devStatus: 'Concluido',
    devType: 'Bug',
    category: 'Suporte',
    complexity: 'Simples',
    resp: 'dev-2',
    createdAt: '2026-03-04',
    updatedAt: '2026-03-07',
    deadline: '2026-03-08',
    totalPts: 2,
    sprintId: 'sp-25',
    prodBug: true,
    criticalBug: true,
  },
  {
    id: 107,
    title: 'Criar pagina de indicadores do CRM',
    devStatus: 'Concluido',
    devType: 'Feature',
    category: 'CRM',
    complexity: 'Complexa',
    resp: 'dev-3',
    createdAt: '2026-03-01',
    updatedAt: '2026-03-13',
    deadline: '2026-03-14',
    totalPts: 8,
    sprintId: 'sp-25',
    docDone: true,
  },
  {
    id: 108,
    title: 'Revisar copy do onboarding',
    devStatus: 'Concluido',
    devType: 'Task',
    category: 'UX',
    complexity: 'Simples',
    resp: 'dev-4',
    createdAt: '2026-02-17',
    updatedAt: '2026-02-19',
    deadline: '2026-02-20',
    totalPts: 2,
    sprintId: 'sp-24',
    docDone: true,
    compliment: true,
  },
  {
    id: 109,
    title: 'Webhook de cobranca com fila',
    devStatus: 'Concluido',
    devType: 'Feature',
    category: 'Financeiro',
    complexity: 'Complexa',
    resp: 'dev-2',
    createdAt: '2026-02-18',
    updatedAt: '2026-02-28',
    deadline: '2026-02-27',
    totalPts: 8,
    sprintId: 'sp-24',
    reopened: true,
    incident: true,
  },
  {
    id: 110,
    title: 'Ajustar ordenacao do kanban dev',
    devStatus: 'Concluido',
    devType: 'Task',
    category: 'Kanban',
    complexity: 'Media',
    resp: 'dev-1',
    createdAt: '2026-02-03',
    updatedAt: '2026-02-06',
    deadline: '2026-02-07',
    totalPts: 3,
    sprintId: 'sp-23',
    docDone: true,
  },
  {
    id: 111,
    title: 'Erro ao salvar integracao do WhatsApp',
    devStatus: 'Concluido',
    devType: 'Bug',
    category: 'Integracoes',
    complexity: 'Media',
    resp: 'dev-3',
    createdAt: '2026-03-09',
    updatedAt: '2026-03-18',
    deadline: '2026-03-15',
    totalPts: 3,
    sprintId: 'sp-26',
    prodBug: true,
    reopened: true,
  },
  {
    id: 112,
    title: 'Novo modal de cadastro de SDR',
    devStatus: 'Concluido',
    devType: 'Feature',
    category: 'Admin',
    complexity: 'Media',
    resp: 'dev-4',
    createdAt: '2026-03-10',
    updatedAt: '2026-03-20',
    deadline: '2026-03-19',
    totalPts: 5,
    sprintId: 'sp-26',
    docDone: false,
  },
  {
    id: 113,
    title: 'Remover regressao no dashboard suporte',
    devStatus: 'Em Desenvolvimento',
    devType: 'Bug',
    category: 'Suporte',
    complexity: 'Media',
    resp: 'dev-1',
    createdAt: '2026-03-18',
    deadline: '2026-03-24',
    totalPts: 3,
    sprintId: 'sp-26',
    criticalBug: true,
  },
  {
    id: 114,
    title: 'Documentar eventos da API interna',
    devStatus: 'Backlog',
    devType: 'Task',
    category: 'Documentacao',
    complexity: 'Simples',
    resp: 'dev-3',
    createdAt: '2026-03-19',
    deadline: '2026-03-30',
    totalPts: 2,
    sprintId: 'sp-26',
  },
  {
    id: 115,
    title: 'Melhorar performance da busca global',
    devStatus: 'Concluido',
    devType: 'Feature',
    category: 'Busca',
    complexity: 'Complexa',
    resp: 'dev-2',
    createdAt: '2026-03-06',
    updatedAt: '2026-03-22',
    deadline: '2026-03-20',
    totalPts: 8,
    sprintId: 'sp-26',
    docDone: true,
    incident: true,
  },
];
